[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.42.9",
    "certifi>=2025.11.12",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "opencv-python>=4.12.0.88",
]
